# Generated by Django 3.1.6 on 2021-03-10 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('coupon', models.CharField(max_length=300)),
                ('is_redeemed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoreName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_names', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_names', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_names', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_name', to='merchants.merchantname')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_name', to='merchants.storename')),
            ],
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('offer', models.PositiveIntegerField(default=0)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('minimum_value', models.PositiveIntegerField()),
                ('date', models.DateField(default='', max_length=300)),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_owner', to='merchants.merchantname')),
            ],
        ),
    ]
